### ISSUE TITLE
Cannot clone repository as out of LFS quota

### ISSUE THREAD

**Issue by Tobias-Fischer** [ros2-gbp/moveit_resources-release#1]
Hiya,

When trying to build moveit-resources packages for RoboStack, we face this issue:
```
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

Could you please take a look?

Many thanks!

**Comment by rhaschke** [comment]
Probably the repository is simply too large. There is nothing we can do about that. Try cloning shallow?

**Comment by Tobias-Fischer** [comment]
I think it’s just the couple of files that are added via LFS. If they were regular files, I don’t think we’d be running into this problem.

**Comment by v4hn** [comment]
git lfs is not required for moveit_resources at the moment (it should also not be used here) and it looks like @sjahr and @henningkayser forgot to remove the `.gitattributes` for lfs again in https://github.com/ros-planning/moveit_resources/pull/173 after it was originally added via https://github.com/ros-planning/moveit_resources/pull/162 last year.

**Comment by Tobias-Fischer** [comment]
Thanks @v4hn - opened a PR at https://github.com/ros-planning/moveit_resources/pull/197

**Comment by sjahr** [comment]
@Tobias-Fischer Thanks for your PR with the fix! Is this issue fixed by  https://github.com/ros-planning/moveit_resources/pull/197?

**Comment by Tobias-Fischer** [comment]
It will be once we have a new release ...

**Comment by traversaro** [comment]
I guess this was closed by https://github.com/ros/rosdistro/pull/40645 ?
